pipeline {
    agent any

    tools {
        nodejs 'NodeJs 18'
    }

    stages {
        stage('Docker Compose Down') {
            steps {
                echo 'Stopping and removing the Docker container named inmind-nginx...'
                dir('FE') {
                    sh '''
                    docker stop inmind-nginx || true
                    docker rm inmind-nginx || true
                    '''
                }
            }
        }

        stage('Docker Compose Up') {
            steps {
                dir('FE') {
                    echo 'Deploying Docker containers...'
                    sh 'docker-compose up --build -d'
                }
            }
        }
    }
}
